version: '3.7'

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rummy-scorekeeper
  postgres:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rummy-scorekeeper

volumes:
  db-data:
